### ISSUE TITLE
Visualisierung

### ISSUE THREAD

**Issue by gRiMMi83** [Asklios/thermav_homeassistant#1]
Hi, was hast du in deiner Version anders gemacht als in der Version von Basti?
Hast du auch ne Visualisierung dazu?
Lese bisher nur mit der Version von Basti aus, muss jetzt aber endlich mal das Steuerungsthema auch mit angehen.

Danke

Gruß Stefan

**Comment by Asklios** [comment]
Hallo,
ich habe die Register anhand der Bedienungsanleitung implementiert, sehe aber keine großen Unterschiede bis auf die Benennungen und die Definition von `data_type` und `state_class` oder die bei `input_number` von `unit_of_measurement` und `icon`
Ziel war es die config etwas standardisierter zu gestalten.
Zur Steuerung verwende ich bisher https://github.com/nielsfaber/scheduler-card
Im Frontend nutze ich einfache tiles, da so eine unbeabsichtigte Änderung vermieden werden kann. Was nicht benötigt wird ist jeweils ausgeblendet.

```
type: vertical-stack
title: Wärmepumpe Einstellungen
cards:
  - type: tile
    entity: switch.enable_disable_heating_cooling
    name: Heizung
    icon: mdi:power
  - type: conditional
    conditions:
      - entity: switch.enable_disable_heating_cooling
        state: "on"
    card:
      type: tile
      entity: input_select.thermav_operation_mode
      name: Operation Mode
  - type: conditional
    conditions:
      - entity: switch.enable_disable_heating_cooling
        state: "on"
      - entity: input_select.thermav_operation_mode
        state: Auto
    card:
      type: tile
      entity: input_number.thermav_auto_mode_target_circuit_1
      name: Offset
  - type: conditional
    conditions:
      - entity: input_select.thermav_operation_mode
        state_not: Auto
    card:
      type: tile
      entity: sensor.therma_v_target_temp_circuit_1
      name: Heizung Temp.
  - type: tile
    entity: switch.enable_disable_dhw
    name: Warmwasser
    icon: mdi:power
  - type: conditional
    conditions:
      - entity: switch.enable_disable_dhw
        state: "on"
    card:
      type: tile
      entity: input_number.thermav_target_temp_ww
      name: Warmwasser Temp.
  - type: conditional
    conditions:
      - entity: switch.enable_disable_heating_cooling
        state: "on"
    card:
      type: tile
      entity: switch.silent_mode_set
      name: Silent Mode
      icon: mdi:power
  - type: entities
    entities:
      - entity: sensor.therma_v_tank_water_temperature
        name: Wassertank
```

![Image](https://github.com/user-attachments/assets/55fe4988-ca81-42e9-abde-4611fb1fc20b)

wenn alles aus ist:

![Image](https://github.com/user-attachments/assets/89add983-ff34-42d8-8fc8-ba25b9622cc4)
